const NON_FOOD_KEYWORDS_DIRECTLY = ['food', 'table'];

const FOOD_GRADE_MAP = [
   { foodName: 'Staple food', nutriScore: 7.5 },
   { foodName: 'Natural foods', nutriScore: 9 },
   { foodName: 'Plant', nutriScore: 9 },
   { foodName: 'Superfood', nutriScore: 9 },
   { foodName: 'Vegetable', nutriScore: 10 },
   { foodName: 'Produce', nutriScore: 5 },
   { foodName: 'Tuber', nutriScore: 8 },
   { foodName: 'Root vegetable', nutriScore: 8 },
   { foodName: 'Potato', nutriScore: 6.5   },

   { foodName: 'Cashew family', nutriScore: 7 },
   { foodName: 'Almond', nutriScore: 7 },
   { foodName: 'Nut', nutriScore: 7 },
   { foodName: 'Nuts & seeds', nutriScore: 7 },

   { foodName: 'Rice', nutriScore: 7.5 },
   { foodName: 'White rice', nutriScore: 7.5 },

   { foodName: 'Fried egg', nutriScore: 7 },
   { foodName: 'Egg white', nutriScore: 9 },
   { foodName: 'Egg yolk', nutriScore: 7 },

   { foodName: 'Sliced bread', nutriScore: 5 },
   { foodName: 'Baked goods', nutriScore: 4 },

   { foodName: 'Confectionery', nutriScore: 1 },
   { foodName: 'Chocolate bar', nutriScore: 1 },
   { foodName: 'Cake', nutriScore: 1 },
   { foodName: 'Snack', nutriScore: 1 },
   { foodName: 'Junk food', nutriScore: 1 },
   { foodName: 'Convenience food', nutriScore: 2 },
   { foodName: 'Food additive', nutriScore: 1 },

   { foodName: 'Deep frying', nutriScore: 1 },
   { foodName: 'Fried food', nutriScore: 1 },
   { foodName: 'Finger food', nutriScore: 1 },
   { foodName: 'Dessert', nutriScore: 1 },
   { foodName: 'Custard', nutriScore: 4 },
   { foodName: 'Ice cream', nutriScore: 3 },
   { foodName: 'Sorbetes', nutriScore: 5 },
   { foodName: 'Gelato', nutriScore: 3 },

   { foodName: 'Fruit', nutriScore: 8 },
   { foodName: 'Strawberry', nutriScore: 6 },

   { foodName: 'Berry', nutriScore: 6 },

   { foodName: 'Watermelon', nutriScore: 8 },
   { foodName: 'Citrullus', nutriScore: 8 },
   { foodName: 'Seedless fruit', nutriScore: 8 },
   { foodName: 'Flowering plant', nutriScore: 9 },
   { foodName: 'Leaf', nutriScore: 9 },

   { foodName: 'Salad', nutriScore: 9 },
   { foodName: 'Seed', nutriScore: 8 },
   { foodName: 'Garden salad', nutriScore: 9 },
   { foodName: 'Salad', nutriScore: 9 },
];

const NON_FOOD_KEYWORDS = [
   'Serve',
   'Wood',
   'Recipe',
   'Plate',
   'Utensil',
   'Cookware',
   'Dish',
   'Cuisine',
   'Dining',
   'Eating',
   'Meal',
   'Ingredient',
   'Food group',
   'Mixture',
   'Container',
   'Drinkware',
   'Glass',
   'Cup',
   'Bowl',
   'Cutlery',
   'Fork',
   'Spoon',
   'Knife',
   'Tray',
   'Napkin',
   'Tableware',
   'Surface',
   'Drink',
   'Beverage',
   'Bottle',
   'Jar',
   'Glass bottle',
   'Decor',
   'Condiment',
   'Spice',
];

const FOOD_KEYWORDS = [
   // Common foods
   'pizza',
   'burger',
   'salad',
   'pasta',
   'soup',
   'sandwich',
   'taco',
   'burrito',
   'wrap',
   'noodles',
   'steak',
   'fries',
   'hotdog',
   'sushi',
   'rice',
   'bread',
   'toast',
   'omelette',
   'pancakes',
   'waffles',

   // Fruits
   'apple',
   'banana',
   'grapes',
   'orange',
   'strawberry',
   'blueberry',
   'raspberry',
   'blackberry',
   'kiwi',
   'pineapple',
   'watermelon',
   'melon',
   'pear',
   'peach',
   'mango',
   'papaya',
   'plum',
   'cherry',
   'lemon',
   'lime',
   'avocado',
   'apricot',

   // Vegetables
   'carrot',
   'broccoli',
   'spinach',
   'kale',
   'lettuce',
   'tomato',
   'cucumber',
   'pepper',
   'potato',
   'sweet potato',
   'onion',
   'garlic',
   'beet',
   'eggplant',
   'zucchini',
   'cauliflower',
   'celery',
   'asparagus',
   'artichoke',
   'cabbage',
   'radish',
   'vegetable',
   'leaf vegetable',

   // Meats and proteins
   'chicken',
   'beef',
   'pork',
   'lamb',
   'bacon',
   'turkey',
   'duck',
   'salmon',
   'tuna',
   'cod',
   'shrimp',
   'lobster',
   'crab',
   'scallops',
   'tofu',
   'tempeh',
   'lentils',
   'beans',
   'quinoa',
   'edamame',
   'eggs',
   'hummus',

   // Dairy
   'milk',
   'cheese',
   'butter',
   'cream',
   'yogurt',
   'ice cream',
   'cottage cheese',
   'mozzarella',
   'cheddar',
   'feta',

   // Grains and cereals
   'oats',
   'granola',
   'cereal',
   'barley',
   'quinoa',
   'bulgur',
   'couscous',
   'brown rice',
   'white rice',
   'pita',
   'bagel',
   'muffin',
   'croissant',
   'scone',
   'toast',
   'tortilla',
   'pancake',
   'waffle',
   'cracker',

   // Snacks and desserts
   'cookie',
   'cake',
   'brownie',
   'cupcake',
   'donut',
   'muffin',
   'candy',
   'chocolate',
   'popcorn',
   'chips',
   'pretzel',
   'granola bar',
   'energy bar',
   'nuts',
   'almonds',
   'peanuts',
   'cashews',
   'walnuts',
   'pistachios',
   'trail mix',
   'ice cream',
   'sorbet',
   'gelato',
   'pudding',

   // Drinks
   'water',
   'coffee',
   'tea',
   'juice',
   'smoothie',
   'milkshake',
   'soda',
   'cola',
   'wine',
   'beer',
   'cocktail',
   'latte',
   'espresso',
   'mocha',
   'lemonade',
   'iced tea',

   // Sauces and condiments
   'ketchup',
   'mustard',
   'mayo',
   'barbecue sauce',
   'ranch',
   'vinaigrette',
   'honey',
   'jam',
   'jelly',
   'syrup',
   'soy sauce',
   'hot sauce',
   'pesto',
   'guacamole',
   'salsa',
   'hummus',
   'tzatziki',

   // Ethnic cuisines
   'ramen',
   'pho',
   'pad thai',
   'curry',
   'naan',
   'tikka masala',
   'biryani',
   'gyoza',
   'dim sum',
   'falafel',
   'shawarma',
   'samosa',
   'gnocchi',
   'risotto',
   'paella',
   'tapas',
   'empanada',
   'enchilada',
   'quesadilla',
   'tamales',
   'poutine',

   // Healthy foods
   'chia seeds',
   'flax seeds',
   'hemp seeds',
   'acai',
   'kefir',
   'kombucha',
   'almond milk',
   'coconut water',
   'smoothie bowl',
   'salmon',
   'avocado toast',
   'quinoa salad',
   'green smoothie',
   'protein shake',
   'energy ball',
   'oatmeal',

   // Junk food and fast food
   'fried chicken',
   'donut',
   'chips',
   'candy',
   'ice cream',
   'cookies',
   'nachos',
   'sliders',
   'milkshake',
   'onion rings',
   'mozzarella sticks',
   'churros',
   'buffalo wings',
   'potato wedges',
   'tater tots',
   'cheese fries',
   'pizza rolls',

   // Other common foods
   'mac and cheese',
   'lasagna',
   'meatballs',
   'stuffed peppers',
   'casserole',
   'chili',
   'frittata',
   'quiche',
   'stromboli',
   'calzone',
   'pierogi',
   'baba ghanoush',
   'spring rolls',
   'dumplings',
   'sushi roll',
   'sashimi',
   'teriyaki',
   'bento box',
];

module.exports = {
   NON_FOOD_KEYWORDS,
   NON_FOOD_KEYWORDS_DIRECTLY,
   FOOD_GRADE_MAP,
};
